# Generated by Django 6.0.3 on 2026-03-06 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название шрифта')),
                ('css_family', models.CharField(help_text='Как шрифт называется в CSS', max_length=200, verbose_name='CSS font-family')),
                ('font_file', models.FileField(blank=True, upload_to='fonts/', verbose_name='Файл шрифта (.ttf/.woff2)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguratorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(help_text='Чистое фоновое изображение товара (табличка без текста)', upload_to='templates/base/', verbose_name='Базовое изображение')),
                ('overlay_mask', models.ImageField(blank=True, help_text='PNG-маска для наложения текстур/материалов', upload_to='templates/masks/', verbose_name='Маска наложения')),
                ('width', models.PositiveIntegerField(default=600, verbose_name='Ширина SVG (px)')),
                ('height', models.PositiveIntegerField(default=400, verbose_name='Высота SVG (px)')),
                ('layers_config', models.JSONField(blank=True, default=dict, help_text='JSON с настройками: {\n  "background_color": "#ffffff",\n  "border_radius": 10,\n  "overlay_opacity": 0.8,\n  "extra_decorations": [\n    {"type": "line", "x1": 0, "y1": 50, "x2": 600, "y2": 50, "stroke": "#ccc"}\n  ]\n}', verbose_name='Конфигурация слоёв')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurator_template', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Шаблон конфигуратора',
                'verbose_name_plural': 'Шаблоны конфигуратора',
            },
        ),
        migrations.CreateModel(
            name='SavedConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('configuration', models.JSONField(default=dict, help_text='{\n  "options": {"material": "brass", "color": "gold"},\n  "texts": {"name": "Иванов И.И.", "title": "Директор"},\n  "font": "Arial"\n}', verbose_name='Конфигурация')),
                ('calculated_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рассчитанная цена')),
                ('preview_image', models.ImageField(blank=True, upload_to='previews/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_configs', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Сохранённая конфигурация',
                'verbose_name_plural': 'Сохранённые конфигурации',
                'ordering': ['-created_at'],
            },
        ),
    ]
