# Generated by Django 6.0.3 on 2026-03-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuratortemplate',
            name='base_image',
            field=models.ImageField(blank=True, help_text='Чистое фоновое изображение товара (табличка без текста). Если не задано — используется фото товара.', upload_to='templates/base/', verbose_name='Базовое изображение'),
        ),
    ]
