# Generated by Django 6.0.3 on 2026-03-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_alter_configuratortemplate_base_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuratortemplate',
            name='real_height_cm',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Настоящая высота изделия в сантиметрах для отображения линейки', max_digits=8, verbose_name='Реальная высота (см)'),
        ),
        migrations.AddField(
            model_name='configuratortemplate',
            name='real_width_cm',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Настоящая ширина изделия в сантиметрах для отображения линейки', max_digits=8, verbose_name='Реальная ширина (см)'),
        ),
    ]
