# Generated by Django 6.0.3 on 2026-03-06 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Материал, Цвет, Шрифт', max_length=200, verbose_name='Название группы')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('widget_type', models.CharField(choices=[('radio', 'Радиокнопки'), ('select', 'Выпадающий список'), ('color', 'Палитра цветов'), ('image', 'Карточки с изображениями')], default='radio', max_length=20, verbose_name='Тип виджета')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Группа атрибутов',
                'verbose_name_plural': 'Группы атрибутов',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Добавляется к базовой цене (может быть отрицательным)', max_digits=10, verbose_name='Модификатор цены')),
                ('image', models.ImageField(blank=True, help_text='Текстура материала, цвет и т.п.', upload_to='options/', verbose_name='Изображение / Текстура')),
                ('color_hex', models.CharField(blank=True, help_text='#RRGGBB — для палитры', max_length=7, verbose_name='Цвет (HEX)')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.attributegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Опция атрибута',
                'verbose_name_plural': 'Опции атрибутов',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Основное изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Произвольные метаданные (SEO, переводы)', verbose_name='Метаданные')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_groups', to='products.product', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='TextFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Например: ФИО, Должность, Надпись', max_length=200, verbose_name='Название поля')),
                ('placeholder', models.CharField(blank=True, max_length=300, verbose_name='Подсказка (placeholder)')),
                ('max_length', models.PositiveIntegerField(default=50, verbose_name='Макс. символов')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('preview_x', models.FloatField(default=50, help_text='Координата X центра текста', verbose_name='X на превью (px)')),
                ('preview_y', models.FloatField(default=50, help_text='Координата Y центра текста', verbose_name='Y на превью (px)')),
                ('preview_font_size', models.FloatField(default=24, verbose_name='Размер шрифта (px)')),
                ('preview_font_family', models.CharField(default='Arial', help_text='CSS font-family', max_length=200, verbose_name='Шрифт')),
                ('preview_color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет текста')),
                ('preview_max_width', models.FloatField(default=300, help_text='Текст сожмётся если превысит', verbose_name='Макс. ширина текста (px)')),
                ('preview_text_anchor', models.CharField(choices=[('start', 'Слева'), ('middle', 'По центру'), ('end', 'Справа')], default='middle', max_length=10, verbose_name='Выравнивание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Текстовое поле',
                'verbose_name_plural': 'Текстовые поля',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='attributegroup',
            unique_together={('product', 'slug')},
        ),
    ]
