# Generated by Django 6.0.3 on 2026-03-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: A4, Стандарт, Большой', max_length=100, verbose_name='Название')),
                ('width', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Высота')),
                ('depth', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='0 — если плоское изделие', max_digits=8, verbose_name='Глубина/Толщина')),
                ('unit', models.CharField(choices=[('mm', 'мм'), ('cm', 'см'), ('m', 'м')], default='mm', max_length=5, verbose_name='Единицы')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, help_text='Добавляется к базовой цене (может быть отрицательным)', max_digits=10, verbose_name='Модификатор цены')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Размер изделия',
                'verbose_name_plural': 'Размеры изделий',
                'ordering': ['sort_order', 'width'],
            },
        ),
    ]
